site_name: rdbc-pool documentation - {{version}}
site_author: Krzysztof Pado
site_dir: target
strict: true
pages:
    - Introduction: index.md
    - Scala API user guide:
      - Installation: scala/installation.md
      - Creating a pool: scala/creating.md
      - Features: scala/features.md
      - Configuration: scala/configuration.md
theme: material

copyright: Copyright &copy; 2016-2017 rdbc contributors

extra:
  version: 1.0
  palette:
    primary: green
    accent: red
  social:
    - type: github
      link: https://github.com/rdbc-io
    - type: twitter
      link: https://twitter.com/rdbc_io

repo_name: rdbc-io/rdbc-pool
repo_url: https://github.com/rdbc-io/rdbc-pool
edit_uri: blob/master/rdbc-pool-doc/docs

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.toc(permalink=true)
  - pymdownx.inlinehilite

extra_css:
  - 'css/extra.css'

google_analytics: ['UA-103140141-1', 'rdbc.io']
